env: "dev"

http_server:
  address: "localhost:8082"

db_type: "postgres" # ðŸ‘ˆ Change this to "postgres" to switch DB

storage_path: "storage/storage.db" # used only for sqlite

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  dbname: "studentdb"
  sslmode: "disable"
