env: "dev"

storage_path: "storage/storage.db"

http_server:
  address: "localhost:8082"

postgres:
  host: "localhost"

  port: 5432

  user: "postgres"

  password: "m"

  dbname: "studentdb"

  sslmode: "disable"
